### PR TITLE
Example/recent case plaintiffs

### PR DESCRIPTION
**Pull request by BeckySharp**
Example use case for:
- given a party and the role they play,
- given date range
- find all the firms that have opposed them,
- aggregate to the firm level the:
  - number of cases where the firm opposed the party
  - attys from the firm from those cases,
  - parties represented by the firm in those cases

### CODE REVIEW

**Comment by BeckySharp** [comment]
also moved the other example up a level in the dir

**Comment by BeckySharp** [comment]
@JustinBrownstone fyi

**Comment by BeckySharp** [comment]
sorry -- had accidentally committed my Client ID/secret.  removed and I have deactivated it.

**Comment by BeckySharp** [comment]
added config to the gitignore

**Review by JesseGCarver — APPROVED** [review]
Yep!

**Pull request merged**
